local ____lualib = base.tsc
local __TS__Class2 = ____lualib.__TS__Class2
ScoreAddWithYearLimitParam = base.tsc.CLASSES.ScoreAddWithYearLimitParam or __TS__Class2("ScoreAddWithYearLimitParam")
ScoreAddWithMonthLimitParam = base.tsc.CLASSES.ScoreAddWithMonthLimitParam or __TS__Class2("ScoreAddWithMonthLimitParam")
ScoreAddWithWeekLimitParam = base.tsc.CLASSES.ScoreAddWithWeekLimitParam or __TS__Class2("ScoreAddWithWeekLimitParam")
ScoreAddWithDayLimitParam = base.tsc.CLASSES.ScoreAddWithDayLimitParam or __TS__Class2("ScoreAddWithDayLimitParam")
ScoreAddWithHourLimitParam = base.tsc.CLASSES.ScoreAddWithHourLimitParam or __TS__Class2("ScoreAddWithHourLimitParam")
Cast = base.tsc.CLASSES.Cast or __TS__Class2("Cast")
RegionCircle = base.tsc.CLASSES.RegionCircle or __TS__Class2("RegionCircle")
RegionRect = base.tsc.CLASSES.RegionRect or __TS__Class2("RegionRect")
Force = base.tsc.CLASSES.Force or __TS__Class2("Force")
CollisionFlags = base.tsc.CLASSES.CollisionFlags or __TS__Class2("CollisionFlags")
ThirdOrderMatrix = base.tsc.CLASSES.ThirdOrderMatrix or __TS__Class2("ThirdOrderMatrix")
PlayerSCEID = base.tsc.CLASSES.PlayerSCEID or __TS__Class2("PlayerSCEID")
MatchTeamID = base.tsc.CLASSES.MatchTeamID or __TS__Class2("MatchTeamID")
MatchInfo = base.tsc.CLASSES.MatchInfo or __TS__Class2("MatchInfo")
Response = base.tsc.CLASSES.Response or __TS__Class2("Response")
ScoreListQueryByUuidParam = base.tsc.CLASSES.ScoreListQueryByUuidParam or __TS__Class2("ScoreListQueryByUuidParam")
ScoreAddWithLimitParam = base.tsc.CLASSES.ScoreAddWithLimitParam or __TS__Class2("ScoreAddWithLimitParam")
ScoreClearParam = base.tsc.CLASSES.ScoreClearParam or __TS__Class2("ScoreClearParam")
Vector = base.tsc.CLASSES.Vector or __TS__Class2("Vector")
ScoreCropData = base.tsc.CLASSES.ScoreCropData or __TS__Class2("ScoreCropData")
crop = base.tsc.CLASSES.crop or __TS__Class2("crop")
QuestCondition = base.tsc.CLASSES.QuestCondition or __TS__Class2("QuestCondition")
Quest = base.tsc.CLASSES.Quest or __TS__Class2("Quest")
SceneObject = base.tsc.CLASSES.SceneObject or __TS__Class2("SceneObject")
UnitPropertyBonus = base.tsc.CLASSES.UnitPropertyBonus or __TS__Class2("UnitPropertyBonus")
ScoreRankAddParam = base.tsc.CLASSES.ScoreRankAddParam or __TS__Class2("ScoreRankAddParam")
ScoreRankSetParam = base.tsc.CLASSES.ScoreRankSetParam or __TS__Class2("ScoreRankSetParam")
autotest_log = base.tsc.CLASSES.autotest_log or __TS__Class2("autotest_log")
UnitBuff = base.tsc.CLASSES.UnitBuff or __TS__Class2("UnitBuff")
DateTime = base.tsc.CLASSES.DateTime or __TS__Class2("DateTime")
os = base.tsc.CLASSES.os or __TS__Class2("os")
ScoreMoneyParam = base.tsc.CLASSES.ScoreMoneyParam or __TS__Class2("ScoreMoneyParam")
ScoreMsgID = base.tsc.CLASSES.ScoreMsgID or __TS__Class2("ScoreMsgID")
ScoreNameData = base.tsc.CLASSES.ScoreNameData or __TS__Class2("ScoreNameData")
ScoreID = base.tsc.CLASSES.ScoreID or __TS__Class2("ScoreID")
ScoreListID = base.tsc.CLASSES.ScoreListID or __TS__Class2("ScoreListID")
ScoreMsgData = base.tsc.CLASSES.ScoreMsgData or __TS__Class2("ScoreMsgData")
ScoreGetRankTotalParam = base.tsc.CLASSES.ScoreGetRankTotalParam or __TS__Class2("ScoreGetRankTotalParam")
ScoreGetRankTotalData = base.tsc.CLASSES.ScoreGetRankTotalData or __TS__Class2("ScoreGetRankTotalData")
ScoreGetUserRankData = base.tsc.CLASSES.ScoreGetUserRankData or __TS__Class2("ScoreGetUserRankData")
ScoreGetRankListData = base.tsc.CLASSES.ScoreGetRankListData or __TS__Class2("ScoreGetRankListData")
ScoreGetUserRankParam = base.tsc.CLASSES.ScoreGetUserRankParam or __TS__Class2("ScoreGetUserRankParam")
ScoreGetRankListParam = base.tsc.CLASSES.ScoreGetRankListParam or __TS__Class2("ScoreGetRankListParam")
ScoreChannelMsgData = base.tsc.CLASSES.ScoreChannelMsgData or __TS__Class2("ScoreChannelMsgData")
ScoreNameSearchParam = base.tsc.CLASSES.ScoreNameSearchParam or __TS__Class2("ScoreNameSearchParam")
ScoreNameNewParam = base.tsc.CLASSES.ScoreNameNewParam or __TS__Class2("ScoreNameNewParam")
ScoreMsgQueryParam = base.tsc.CLASSES.ScoreMsgQueryParam or __TS__Class2("ScoreMsgQueryParam")
ScoreMsgSendParam = base.tsc.CLASSES.ScoreMsgSendParam or __TS__Class2("ScoreMsgSendParam")
ScoreListData = base.tsc.CLASSES.ScoreListData or __TS__Class2("ScoreListData")
ScoreListDeleteParam = base.tsc.CLASSES.ScoreListDeleteParam or __TS__Class2("ScoreListDeleteParam")
ScoreListModifyParam = base.tsc.CLASSES.ScoreListModifyParam or __TS__Class2("ScoreListModifyParam")
ScoreListAddParam = base.tsc.CLASSES.ScoreListAddParam or __TS__Class2("ScoreListAddParam")
ScoreMoneyData = base.tsc.CLASSES.ScoreMoneyData or __TS__Class2("ScoreMoneyData")
ScoreAddParam = base.tsc.CLASSES.ScoreAddParam or __TS__Class2("ScoreAddParam")
ScoreSetParam = base.tsc.CLASSES.ScoreSetParam or __TS__Class2("ScoreSetParam")
ScoreData = base.tsc.CLASSES.ScoreData or __TS__Class2("ScoreData")
UserID = base.tsc.CLASSES.UserID or __TS__Class2("UserID")
ScoreGetParam = base.tsc.CLASSES.ScoreGetParam or __TS__Class2("ScoreGetParam")
ScoreObjData = base.tsc.CLASSES.ScoreObjData or __TS__Class2("ScoreObjData")
ScoreCommitter = base.tsc.CLASSES.ScoreCommitter or __TS__Class2("ScoreCommitter")
AISearcher = base.tsc.CLASSES.AISearcher or __TS__Class2("AISearcher")
DataCache = base.tsc.CLASSES.DataCache or __TS__Class2("DataCache")
Sight = base.tsc.CLASSES.Sight or __TS__Class2("Sight")
UnitGroup = base.tsc.CLASSES.UnitGroup or __TS__Class2("UnitGroup")
Line = base.tsc.CLASSES.Line or __TS__Class2("Line")
Trigger = base.tsc.CLASSES.Trigger or __TS__Class2("Trigger")
Player = base.tsc.CLASSES.Player or __TS__Class2("Player")
Inventory = base.tsc.CLASSES.Inventory or __TS__Class2("Inventory")
Skill = base.tsc.CLASSES.Skill or __TS__Class2("Skill")
Slot = base.tsc.CLASSES.Slot or __TS__Class2("Slot")
DamageInstance = base.tsc.CLASSES.DamageInstance or __TS__Class2("DamageInstance")
TriggerEvent = base.tsc.CLASSES.TriggerEvent or __TS__Class2("TriggerEvent")
HealInstance = base.tsc.CLASSES.HealInstance or __TS__Class2("HealInstance")
Buff = base.tsc.CLASSES.Buff or __TS__Class2("Buff")
Unit = base.tsc.CLASSES.Unit or __TS__Class2("Unit")
Mover = base.tsc.CLASSES.Mover or __TS__Class2("Mover")
Point = base.tsc.CLASSES.Point or __TS__Class2("Point")
EffectParam = base.tsc.CLASSES.EffectParam or __TS__Class2("EffectParam")
UnitTable = base.tsc.CLASSES.UnitTable or __TS__Class2("UnitTable")
Target = base.tsc.CLASSES.Target or __TS__Class2("Target")
ScreenPos = base.tsc.CLASSES.ScreenPos or __TS__Class2("ScreenPos")
Region = base.tsc.CLASSES.Region or __TS__Class2("Region")
Item = base.tsc.CLASSES.Item or __TS__Class2("Item")
TriggerParamTable = base.tsc.CLASSES.TriggerParamTable or __TS__Class2("TriggerParamTable")
EffectParamShared = base.tsc.CLASSES.EffectParamShared or __TS__Class2("EffectParamShared")
Snapshot = base.tsc.CLASSES.Snapshot or __TS__Class2("Snapshot")
Timer = base.tsc.CLASSES.Timer or __TS__Class2("Timer")
Team = base.tsc.CLASSES.Team or __TS__Class2("Team")
Actor = base.tsc.CLASSES.Actor or __TS__Class2("Actor")
Coroutine = base.tsc.CLASSES.Coroutine or __TS__Class2("Coroutine")
IEventNotify = base.tsc.CLASSES.IEventNotify or __TS__Class2("IEventNotify")
Present = base.tsc.CLASSES.Present or __TS__Class2("Present")
Array = base.tsc.CLASSES.Array or __TS__Class2("Array")
p_0tja = p_0tja or ({})
do
    local function _TRIG_克里夫_FUNC(当前触发器, e)
        local 新变量 = base.rect(
            base.scene_point(1000, 10000, 0, "default"),
            500,
            500,
            "default"
        )
        local 新变量_1 = base.circle(
            base.scene_point(1000, 10000, 0, "default"),
            500,
            "default"
        )
        if true then
        end
    end
    p_0tja.克里夫 = base.trigger_new(
        function(当前触发器, e)
            _TRIG_克里夫_FUNC(当前触发器, e)
        end,
        {},
        false,
        nil,
        true
    )
    p_0tja.克里夫:add_event_common({obj = base.game, event_name = "游戏-开始"})
end
